# Generated by Django 3.0.3 on 2020-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0002_auto_20200226_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
