# Generated by Django 3.0.3 on 2020-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0004_auto_20200226_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='plan',
            field=models.CharField(choices=[('Video-report', 'Video-report'), ('Video-colloquio', 'Video-colloquio'), ('Website', 'Website'), ('Social media manager', 'Social media manager'), ('Unknown', 'Unknown')], default='Video-report', max_length=25),
        ),
    ]
