# Generated by Django 3.0.3 on 2020-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('webpage', models.CharField(max_length=256)),
                ('sn_facebook', models.BooleanField(default=False)),
                ('sn_instagram', models.BooleanField(default=False)),
                ('sn_twitter', models.BooleanField(default=False)),
                ('sn_tiktok', models.BooleanField(default=False)),
                ('sn_linkedin', models.BooleanField(default=False)),
                ('sn_snapchat', models.BooleanField(default=False)),
                ('sn_pinterest', models.BooleanField(default=False)),
                ('session_key', models.CharField(max_length=32)),
                ('purchased', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
