# Generated by Django 3.0.3 on 2020-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='plan',
            field=models.CharField(choices=[('Video-report', 'Video-report'), ('Video-colloquio', 'Video-colloquio'), ('Social media manager', 'Social media manager'), ('Unknown', 'Unknown')], default='Video-report', max_length=25),
        ),
    ]
