# Generated by Django 3.0.3 on 2020-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200219_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='plan',
            field=models.CharField(choices=[('Video-report', 'Video-report'), ('Video-colloquio', 'Video-colloquio'), ('Piano su misura', 'Piano su misura')], default='Video-report', max_length=25),
        ),
    ]
