# Generated by Django 3.0.3 on 2020-02-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_paymentintent_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentIntent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.PaymentIntent'),
        ),
    ]
