# Generated by Django 3.0.3 on 2020-02-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_paymentintent_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payer_email', models.CharField(max_length=256)),
                ('payer_id', models.CharField(max_length=256)),
                ('payer_status', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('txn_id', models.CharField(max_length=256, unique=True)),
                ('txn_type', models.CharField(max_length=256)),
                ('mc_currency', models.CharField(max_length=256)),
                ('payment_fee', models.FloatField()),
                ('payment_gross', models.FloatField()),
                ('payment_status', models.CharField(max_length=256)),
                ('payment_type', models.CharField(max_length=256)),
                ('item_name', models.CharField(max_length=256)),
                ('payment_date', models.DateTimeField()),
                ('custom', models.CharField(max_length=256)),
                ('verify_sign', models.CharField(max_length=256)),
                ('paymentIntent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.PaymentIntent')),
            ],
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='browser_family',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='browser_version',
            field=models.CharField(default='0', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_brand',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_family',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_is_bot',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_is_mobile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_is_pc',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_is_tablet',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_is_touch_capable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='device_model',
            field=models.CharField(default=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='os_family',
            field=models.CharField(default=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='os_version',
            field=models.CharField(default=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='screen_height',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='screen_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='user_agent',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='plan',
            field=models.CharField(choices=[('Video-report', 'Video-report'), ('Video-colloquio', 'Video-colloquio'), ('Social media manager', 'Social media manager')], default='Video-report', max_length=25),
        ),
    ]
