# Generated by Django 3.0.3 on 2020-02-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200224_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='browser_family',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='browser_version',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_brand',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_family',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_is_touch_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device_model',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='os_family',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='os_version',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='screen_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='screen_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
