# Generated by Django 3.0.3 on 2020-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200224_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_revenue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
