# Generated by Django 3.0.3 on 2020-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_payment_payment_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='custom',
            new_name='session_key',
        ),
    ]
