# Generated by Django 3.0.3 on 2020-02-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200224_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='session_key',
            new_name='payment_intent_id',
        ),
    ]
