# Generated by Django 3.0.3 on 2020-02-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200224_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentintent',
            old_name='session_key',
            new_name='payment_intent_id',
        ),
    ]
