# Generated by Django 3.0.3 on 2020-02-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200224_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='payment_intent_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
