# Generated by Django 3.0.3 on 2020-02-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_payment_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentIntent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.PaymentIntent'),
        ),
    ]
